### ISSUE TITLE
Wrong JSON, it must have an empty key ("") with "language" and "plural-forms" information

### ISSUE THREAD

**Issue by nickbrit** [Wisembly/ember-gettext#2]
I'm trying to use ember-gettext:

`Ember.I18n.loadJSON({
    "": {
        "lang": "fr",
        "plural_forms": "nplurals=2; plural=(n!=1);"
    },
    "Welcome": "It's tranlation",
    "another with %1 parameter": "It's %1 tranlsation",
    "a key with plural": [
        "a plural form",
        "another plural form",
        "could have up to 6 forms with some languages"
    ],
    "a context\u0004a contextualized key": "translation here"
});
Ember.I18n.setLocate('fr');`

But I'm getting this error:
`Wrong JSON, it must have an empty key ("") with "language" and "plural-forms" information`

**Comment by guillaumepotier** [comment]
Hi,

It seems that the JSON you're passing does not have the expected keys. Instead of `lang` it expects `language` and instead of `plural_forms` it expects `plural-forms`.

Writing that, I see that you followed [the format here](https://github.com/guillaumepotier/gettext.js#required-json-format) and it might have changed in the code, not in the readme. (expecting [that in the code](https://github.com/guillaumepotier/gettext.js/blob/master/lib/gettext.js)). Could you have a try ?

Best

**Comment by nickbrit** [comment]
It works. Thank you.
Now I'm getting `Uncaught TypeError: Ember.I18n.setLocate is not a function`. But `<html lang="fr">` works.
